### ISSUE TITLE
create perception function

### ISSUE THREAD

**Issue by nickno7** [lucasthierry17/Ant_Project#13]
Please create a first function for the perception of the ant. The function should define in what radius the ant can sense food or other pheromones.

**Comment by nickno7** [comment]
Hey I added a simple implementation of the ants perception and a possible way to approach the food.
It calculates the distance to each food spot and then saves the food spots that are in a specific perception radius in a list.
The approach_food function then calculates the nearest detected food spot and instructs the ant to approach that food spot.
I worked with the movement function that @lucasthierry17 implemented. For better understanding I marked the ants that detect a food spot as red crosses. So you can see how the ants sense a food spot in their perception radius and then approach that food spot.
Here is the link of my code: https://github.com/lucasthierry17/Ant_Project/blob/nick/dummy_files/main.py

I think the next step is to code the pheromones of the ants.

**Comment by lucasthierry17** [comment]
Nice work, just tested the code and it works like expected. Just a couple of things. Could you please provide some more explanation in the comments, how the function works, I think it might help for the understanding. Also, what condition has to be met so that the ants "loose" their red colour and return to the colour blue?
