### ISSUE TITLE
Food Pheromones

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#43]
Please add the food pheromones similarly to the home_pheromones. They should be colored in green.

**Comment by lucasthierry17** [comment]
Hi, as a first try, I added the food_pheromones for each ant, that is crossing a food_source. Also, when the ants walk over the nest and they have the status "has_food" they loose this status again. 
But I have one problem. If there is a value in the position an ant walks over, the pheromone value is not updated. 
@nickno7 Please go through the code and let me know if you find the error. 
The movement function has not been changed, this will have to be done in another step. Please go through the code, test it and let me know if there any problems you are encountering. You can review the code here: https://github.com/lucasthierry17/Ant_Project/blob/lucas/pygame_grids.py

**Comment by nickno7** [comment]
Hey, your code works!

Unfortunately I couldn't solve the problem yet. Maybe you could help to identify what we have to change in order to update the values of pheromones in positions where pheromones already are placed. @Fouad1806 @svenatgithub  
So that the weak pheromones get refreshed when other ants go over that position and place their pheromone trail.

**Comment by Fouad1806** [comment]
So I uploadad a new main.py in my branch, which integrates a backend_pherone method, that is important to manipulate the movemant of the ant. If they use this as their orientation, we sucessfully manage to get it look like as if the ants follow the visualized pheromones. Like we discussed in Teams.

**Comment by nickno7** [comment]
We've successfully implemented the green pheromones, when the ant is carrying food.
